 #include <stdlib.h>  
 #include <stdio.h>  
 #include <string.h>  
 void main()  
 {  
   const int folder = 4;  
   char a[4][20];  
   strcpy(a[0],"Images");  
   strcpy(a[1],"Videos");  
   strcpy(a[2],"Documents");  
   strcpy(a[3],"Audio");  
   char buffer[100];  

   for (int i=0; i < folder; ++i)  
   {  
     printf("\nGive Folder Name for your %s: ",a[i]);  
     gets(a[i]);  
     sprintf(buffer,"mkdir \"%s\"",a[i]);  
     system(buffer);  
     if(i==0)  //All Image Files
     {  
       sprintf(buffer, "move *.ico \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.jpeg \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.png \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.tif \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.tiff \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.bmp \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.jpg \"%s\"", a[i]);  
       system(buffer);   
       system("cls");  
     }  
     else if(i==1)  //All Video Files
     {  
       sprintf(buffer, "move *.avi \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.flv \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.3gp \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.mpg \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *mpeg \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.wmv \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.mov \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.ogg \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.webm \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.mkv \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.ogv \"%s\"", a[i]);  
       system(buffer);    
       sprintf(buffer, "move *.gifv \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.gif \"%s\"", a[i]);  
       system(buffer);  
       system("cls");  
     }  
     else if(i==2)  //All Documents and Other Files
     {  
       sprintf(buffer, "move *.doc \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.docx \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.ppt \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.pptx \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.pps \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.pdf \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.odt \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.rtf \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.tex \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.wps \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.wpd \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.zip \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.rar \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.sql \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.xml \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.apk \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *com \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.bat \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.py \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.bin \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.c \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.js \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.cpp \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.class \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.java \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.cs \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.h \"%s\"", a[i]);  
       system(buffer);    
       sprintf(buffer, "move *.vb \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.ods \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.xlr \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.xls \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.xlsx \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.bak \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.tmp \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.ini \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.cpl \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.dmp \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.1st \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.ans \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.ascii \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.bib \"%s\"", a[i]);  
       system(buffer);   
       sprintf(buffer, "move *.dmp \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.dropbox \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.readme \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.emlx \"%s\"", a[i]);  
       system(buffer);  
       system("cls");  
     }  
     else if(i==3)  //All Audio Files
     {  
       sprintf(buffer, "move *.3ga \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.4mp \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.5xb \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.5xe \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.669 \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.a2b \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.aa \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.aa3 \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.aax \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.abc \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.ac3 \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.acp \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.aiff \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.all \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.aob \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.bwf \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.cda \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.cel \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.cpr \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.dcm \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.dmsa \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.dss \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.dtm \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.f64 \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.flac \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.gp5 \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.hca \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.iff \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.iti \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.kar \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.m3u \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.m4r \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.m5p \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.mdc \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.mid \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.mka \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.mmf \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.mp3 \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.mpu \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.mxl \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.nkc \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.pca \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.pcg \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.pek \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.ra \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.raw \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.rgrp \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.rmj \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.rti \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.slp \"%s\"", a[i]);  
       system(buffer);  
       sprintf(buffer, "move *.vlc \"%s\"", a[i]);  
       system(buffer);  
       system("cls");  
     }  
   }  
 } 